apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  # application
  - containerPort: 30000
    hostPort: 30000
  # apis
  - containerPort: 30080
    hostPort: 30080
  # postgres database
  - containerPort: 31321
    hostPort: 31321
  # Grafana
  - containerPort: 31300
    hostPort: 31300
- role: worker
- role: worker

